# Generated by Django 6.1 on 2026-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected annual return percentage (e.g. 8.50 for 8.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
