# Generated by Django 6.1 on 2026-09-04 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Claim', 'verbose_name_plural': 'Claims'},
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('investment__isnull', False)), fields=('claimant', 'investment'), name='unique_claim_per_investment'),
        ),
    ]
