# Generated by Django 6.1 on 2026-09-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, help_text='Risk score (0-100)', null=True)),
                ('level', models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=20)),
                ('factors', models.JSONField(blank=True, default=dict, help_text='Risk factors and their weights')),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='projects.project')),
            ],
            options={
                'verbose_name': 'Évaluation de risque',
                'verbose_name_plural': 'Évaluations de risque',
            },
        ),
    ]
