# Generated by Django 6.1 on 2026-09-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_coverage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('premium_rate', models.DecimalField(decimal_places=2, help_text='Taux de prime en pourcentage', max_digits=5)),
                ('risk_levels', models.JSONField(default=list, help_text="Liste des niveaux de risque couverts: ['LOW', 'MEDIUM', 'HIGH']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('KYC_SUMMARY', 'Résumé KYC'), ('RISK_ANALYSIS', 'Analyse des risques'), ('COVERAGE_REPORT', 'Rapport de couverture'), ('PORTFOLIO_SUMMARY', 'Résumé du portefeuille')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
